name = "cell"
version = "1.0.0"
gleam = ">= 1.11.0"
description = "Mutable references that can be concurrently accessed, based on ETS tables"
licences = ["Apache-2.0"]
repository = { type = "github", user = "lpil", repo = "cell" }
links = [
  { title = "Sponsor", href = "https://github.com/sponsors/lpil" },
]

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
